#!/usr/bin/python3

import cv2
import numpy as np
import joystick

## Change variable definitions here:
# Panning
pan_speed = 10

# Zooming
zoom_speed = 10
max_zoom = 200

# Specify Display Dimensions
roi_x = 1980
roi_y = 1200
ratio = roi_x/roi_y

# Choose how many pixels to crop vertically
v_margins = 310
new_height = 960 - 2 * v_margins

# Initialize variables    
shift = 0
zoom = 0

# Initialize Joystick Object
joystick = joystick.Joystick()
joystick.start()

# Connect to Theta V for Live Footage
capture = cv2.VideoCapture("thetauvcsrc mode=2K ! h264parse ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! videoconvert ! video/x-raw,format=BGR ! queue ! appsink")

# Play Pre-recorded Video
#capture = cv2.VideoCapture(r"/home/aquariscope/Desktop/Rivervideo360 - Made with Clipchamp.mp4")

if not capture.isOpened():
    print("Cannot open camera")
    exit()

## Video Capture Loop
while True:
    ret, frame = capture.read()
    if not ret:
        print("Cannot receive frame")
        break

    # Crop top and bottom of feed to remove obscured regions
    cropped_frame = frame[v_margins:960-v_margins, 0:1920]    
    
    # Pad frame with extra ROI width to enable 360 rotation
    half_frame = cropped_frame[:, 0:int(roi_x)]
    padded_frame = np.hstack((cropped_frame, half_frame))
    
    # Crop to region of interest (ROI)
    shift = shift%cropped_frame.shape[1]
    roi = padded_frame[zoom:new_height-zoom, ((0+shift)%(padded_frame.shape[1]))+int(2*zoom*ratio):((roi_x+shift)%(padded_frame.shape[1]))-int(2*zoom*ratio)]

    # Resize to specified monitor dimensions and flip image
    finalImage = cv2.flip(finalImage, 0)
    finalImage = cv2.resize(finalImage, (1980, 1200))
    cv2.imshow('Livecam View', finalImage) 
    
    key = cv2.waitKey(20) & 0xFF

    # Keyboard and joystick bindings
    # Note, escape or q to break window! X button does not work for default OpenCV
    if key == ord('q') or key == 27:
        break
    elif key == ord('a') or values[0]:
        shift -= pan_speed
    elif key == ord('d') or values[1]:
        shift += pan_speed
    elif key == ord('w') or values[2]:
        zoom += zoom_speed
    elif key == ord('s') or values[3]:
        zoom -= zoom_speed
        
    if zoom <= 0:
        zoom = 0
    elif zoom >=max_zoom:
        zoom = max_zoom

# End feed
capture.release()
cv2.destroyAllWindows()


